name: ord_countdown
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7
  shared_preferences_macos: ^0.0.1+1
  shared_preferences_web: ^0.1.2+1
  intl: ^0.16.1
  flutter_hsvcolor_picker: ^0.0.1
#  hive: ^1.4.1+1
#  hive_flutter: ^0.3.0+2
#  path_provider: ^1.4.0
  flutter_circular_chart: ^0.1.0
  url_launcher: ^4.0.3
  flutter_colorpicker: ^0.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: OpenSans    
      fonts:
        - asset: assets/OpenSans-Regular.ttf
        - asset: assets/OpenSans-Light.ttf
          style: italic
        - asset: assets/OpenSans-Bold.ttf
          weight: 700

